STRING = "HELLO WORLD"
SLICIED_STRING = STRING[2:9]
SLICIED_STRING_JUMPED = STRING[2:9:3]
NEGATIVE_SLICED_STRING = STRING[-8:-3]
print(f"{SLICIED_STRING=}")
print(f"{SLICIED_STRING_JUMPED=}")
print(f"{NEGATIVE_SLICED_STRING=}")
#OUTPUT
"""
SLICIED_STRING='LLO WOR'
SLICIED_STRING_JUMPED='L R'
NEGATIVE_SLICED_STRING='LO WO'
"""